//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eksamensopgave2016.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eksamensopgave2016.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id;name;price;active;deactivate_date
        ///1;Diverse;100;0;
        ///2;&quot;½L Letmælk&quot;;450;0;
        ///3;&quot;¼L Letmælk&quot;;250;0;
        ///4;&quot;¼L Skummetmælk&quot;;225;0;
        ///5;&quot;¼L Kærnemælk&quot;;225;0;
        ///6;&quot;¼L Øko Letmælk&quot;;275;0;
        ///7;&quot;¼L Øko Skummetmælk&quot;;250;0;
        ///8;&quot;½L Skummetmælk (2x¼)&quot;;375;0;
        ///9;&quot;1L Letmælk&quot;;600;0;
        ///10;&quot;½L Kærnemælk (2x¼)&quot;;525;0;
        ///11;&quot;½L vand &amp; kildevand excl. pant&quot;;1200;1;
        ///12;&quot;¼L Sodavand&quot;;500;0;
        ///13;&quot;Øl(f.eks. Thy, Guld, 47, T-FF)&quot;;1000;1;
        ///14;Øl(Tuborg/Classic/Carlsberg/Rød);650;1;
        ///15;&quot;Øl(Staropramen, Corona, Budweis)&quot;;1500;1;
        ///16;Cocio;1600;1;
        ///17;&quot;½ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TransactionLogfile {
            get {
                return ResourceManager.GetString("TransactionLogfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Userlist {
            get {
                return ResourceManager.GetString("Userlist", resourceCulture);
            }
        }
    }
}
